# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target 'WalletApp' do
 pod 'MagicalRecord/Shorthand'
 pod 'SwiftyJSON'
end