source 'https://github.com/CocoaPods/Specs.git'

# Define a global platform for the project
platform :ios, '8.0'

target 'WalletApp' do
# Add dependencies

# CORE DATA
pod 'MagicalRecord/Shorthand'

end